function Hd = fir256
%FIR256 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 16-Jul-2016 23:01:23

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 240;  % Sampling Frequency

N    = 256;      % Order
Fc1  = 0.5;      % First Cutoff Frequency
Fc2  = 30;       % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter
% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
